### ISSUE TITLE
Full update of Social Profiles & Social Followers Counter modules

### ISSUE THREAD

**Issue by appscreo** [appscreo/easy-social-share-buttons3#184]
- [x] Inline SVG icon migration
- [x] Clean up and reduce style size
- [x] New customizer of styles
- [x] Profiles widget for Elementor
- [x] Clear deprecated networks from the list and code
