### ISSUE TITLE
[Social Followers/Profiles] Include the ability users to add own buttons into Social Profiles and Social Followers Counter (manual counter).

### ISSUE THREAD

**Issue by appscreo** [appscreo/easy-social-share-buttons3#8]
Planned:

- [ ] Create the network name inside the followers options
- [ ] Setup custom background, text color, SVG icon
- [ ] Integrate automatically into Social Followers (manual counter) and Social Profiles
